[package]
name = "example"
edition.workspace = true
version.workspace = true

[dependencies]
libadwaita = "0.7"
gtk4 = "0.9"
clapper = { path = "../libclapper-rs" }
clapper-gtk = { path = "../libclapper-gtk-rs" }
