#!/bin/sh
set -e

case "$1" in
    configure)
        # extract locale files
        if [ -f /usr/share/tsukimi_locale.tar.gz ]; then
            echo "Extracting locale files..."
            tar -xzf /usr/share/tsukimi_locale.tar.gz -C /usr/share/
            rm -f /usr/share/tsukimi_locale.tar.gz
        fi

        # update gschemas
        if [ -x /usr/bin/glib-compile-schemas ]; then
          echo "Updating GLib schemas..."
          /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
        else
          echo "Error: glib-compile-schemas not found!" >&2
          exit 1
        fi
        ;;
esac

exit 0
