name: Build migtool
on:
  workflow_dispatch:
  push:
    tags:
      - migtool*

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_BACKTRACE: full

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        timeout-minutes: 20
        run: |
          rustup default stable-msvc
          cargo b -r

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tsukimi-migtool
          path: |
            target/release/*.exe

      - name: Get release tag
        run: |
          write-host "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/*.exe
          tag_name: ${{ env.TAG_NAME }}
